blank_issues_enabled: false
contact_links:
  - name: Abteilung WebIT Dashboard Diskussion
    url: https://github.com/sbw-neue-medien/abteilung-webit-dash/discussion
    about: Diskutieren neue und bestehenden Features
