blank_issues_enabled: false
contact_links:
  - name: SBW Neue Medien Materialverleih Support
    url: https://github.com/sbw-neue-medien/mv-webpage/discussion
    about: Diskutieren neue und bestehenden Features
